- name: Stop application
  docker_compose:
    project_src: "/opt/composes/{{ image }}"
    state: absent
- name: Delete the image from docker
  docker_image:
    name: "{{ image }}"
    state: absent

- name: Remove the compose directory
  ansible.builtin.file:
    path: "/opt/composes/{{ image }}"
    state: absent